from django.db import models


class Match(models.Model):
    date = models.DateTimeField()
    home_team = models.CharField(max_length=100)
    away_team = models.CharField(max_length=100)
    full_time_home_goals = models.IntegerField()
    full_time_away_goals = models.IntegerField()
    full_time_result = models.CharField(max_length=10)
    half_time_home_goals = models.IntegerField()
    half_time_away_goals = models.IntegerField()
    half_time_result = models.CharField(max_length=10)
    referee = models.CharField(max_length=100)
    home_team_shots = models.IntegerField()
    away_team_shots = models.IntegerField()
    home_team_shots_on_target = models.IntegerField()
    away_team_shots_on_target = models.IntegerField()
    home_team_hit_woodwork = models.IntegerField(null=True)
    away_team_hit_woodwork = models.IntegerField(null=True)
    home_team_corners = models.IntegerField()
    away_team_corners = models.IntegerField()
    home_team_fouls_commited = models.IntegerField()
    away_team_fouls_commited = models.IntegerField()
    home_team_offsides = models.IntegerField(null=True)
    away_team_offsides = models.IntegerField(null=True)
    home_team_yellow_cards = models.IntegerField()
    away_team_yellow_cards = models.IntegerField()
    home_team_red_cards = models.IntegerField()
    away_team_red_cards = models.IntegerField()


class Totals(models.Model):
    match_id = models.ForeignKey(
        'Match',
        db_index=True,
        null=False,
        on_delete=models.DO_NOTHING,
    )
    home_team_total_goal_full_time = models.IntegerField()
    away_team_total_goal_full_time = models.IntegerField()
    home_team_total_goal_full_time_as_home = models.IntegerField()
    away_team_total_goal_full_time_as_away = models.IntegerField()
    home_team_total_goal_half_time = models.IntegerField()
    away_team_total_goal_half_time = models.IntegerField()
    home_team_total_goal_half_time_as_home = models.IntegerField()
    away_team_total_goal_half_time_as_away = models.IntegerField()
    home_team_total_goal_second_half_time = models.IntegerField()
    away_team_total_goal_second_half_time = models.IntegerField()
    home_team_total_goal_second_half_time_as_home = models.IntegerField()
    away_team_total_goal_second_half_time_as_away = models.IntegerField()
    home_team_total_goal_conceded_full_time = models.IntegerField()
    away_team_total_goal_conceded_full_time = models.IntegerField()
    home_team_total_goal_conceded_full_time_as_home = models.IntegerField()
    away_team_total_goal_conceded_full_time_as_away = models.IntegerField()
    home_team_total_goal_conceded_half_time = models.IntegerField()
    away_team_total_goal_conceded_half_time = models.IntegerField()
    home_team_total_goal_conceded_half_time_as_home = models.IntegerField()
    away_team_total_goal_conceded_half_time_as_away = models.IntegerField()
    home_team_total_goal_conceded_second_half_time = models.IntegerField()
    away_team_total_goal_conceded_second_half_time = models.IntegerField()
    home_team_total_goal_conceded_second_half_time_as_home = models.IntegerField()
    away_team_total_goal_conceded_second_half_time_as_away = models.IntegerField()
    home_team_total_shots = models.IntegerField()
    away_team_total_shots = models.IntegerField()
    home_team_total_shots_as_home = models.IntegerField()
    away_team_total_shots_as_away = models.IntegerField()
    home_team_total_shots_on_target = models.IntegerField()
    away_team_total_shots_on_target = models.IntegerField()
    home_team_total_shots_on_target_as_home = models.IntegerField()
    away_team_total_shots_on_target_as_away = models.IntegerField()
    home_team_total_shots_conceded = models.IntegerField()
    away_team_total_shots_conceded = models.IntegerField()
    home_team_total_shots_conceded_as_home = models.IntegerField()
    away_team_total_shots_conceded_as_away = models.IntegerField()
    home_team_total_shots_conceded_on_target = models.IntegerField()
    away_team_total_shots_conceded_on_target = models.IntegerField()
    home_team_total_shots_conceded_on_target_as_home = models.IntegerField()
    away_team_total_shots_conceded_on_target_as_away = models.IntegerField()
    home_team_total_fouls_commited = models.IntegerField()
    away_team_total_fouls_commited = models.IntegerField()
    home_team_total_fouls_commited_as_home = models.IntegerField()
    away_team_total_fouls_commited_as_away = models.IntegerField()
    home_team_total_fouls_conceded = models.IntegerField()
    away_team_total_fouls_conceded = models.IntegerField()
    home_team_total_fouls_conceded_as_home = models.IntegerField()
    away_team_total_fouls_conceded_as_away = models.IntegerField()
    home_team_total_corners = models.IntegerField()
    away_team_total_corners = models.IntegerField()
    home_team_total_corners_as_home = models.IntegerField()
    away_team_total_corners_as_away = models.IntegerField()
    home_team_total_corners_conceded = models.IntegerField()
    away_team_total_corners_conceded = models.IntegerField()
    home_team_total_corners_conceded_as_home = models.IntegerField()
    away_team_total_corners_conceded_as_away = models.IntegerField()
    home_team_total_yellow_cards = models.IntegerField()
    away_team_total_yellow_cards = models.IntegerField()
    home_team_total_yellow_cards_as_home = models.IntegerField()
    away_team_total_yellow_cards_as_away = models.IntegerField()
    home_team_total_yellow_cards_conceded = models.IntegerField()
    away_team_total_yellow_cards_conceded = models.IntegerField()
    home_team_total_yellow_cards_conceded_as_home = models.IntegerField()
    away_team_total_yellow_cards_conceded_as_away = models.IntegerField()
    home_team_total_red_cards = models.IntegerField()
    away_team_total_red_cards = models.IntegerField()
    home_team_total_red_cards_as_home = models.IntegerField()
    away_team_total_red_cards_as_away = models.IntegerField()
    home_team_total_red_cards_conceded = models.IntegerField()
    away_team_total_red_cards_conceded = models.IntegerField()
    home_team_total_red_cards_conceded_as_home = models.IntegerField()
    away_team_total_red_cards_conceded_as_away = models.IntegerField()


class Referee(models.Model):
    name = models.CharField(max_length=100)
    home_yellow_cards = models.IntegerField()
    away_yellow_cards = models.IntegerField()
    home_red_cards = models.IntegerField()
    away_red_cards = models.IntegerField()
    num_matches = models.IntegerField()
