# Generated by Django 3.0.3 on 2020-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('full_time_home_goals', models.IntegerField()),
                ('full_time_away_goals', models.IntegerField()),
                ('full_time_result', models.CharField(max_length=10)),
                ('half_time_home_goals', models.IntegerField()),
                ('half_time_away_goals', models.IntegerField()),
                ('half_time_result', models.CharField(max_length=10)),
                ('referee', models.CharField(max_length=100)),
                ('home_team_shots', models.IntegerField()),
                ('away_team_shots', models.IntegerField()),
                ('home_team_shots_on_target', models.IntegerField()),
                ('away_team_shots_on_target', models.IntegerField()),
                ('home_team_hit_woodwork', models.IntegerField(null=True)),
                ('away_team_hit_woodwork', models.IntegerField(null=True)),
                ('home_team_corners', models.IntegerField()),
                ('away_team_corners', models.IntegerField()),
                ('home_team_fouls_commited', models.IntegerField()),
                ('away_team_fouls_commited', models.IntegerField()),
                ('home_team_offsides', models.IntegerField(null=True)),
                ('away_team_offsides', models.IntegerField(null=True)),
                ('home_team_yellow_cards', models.IntegerField()),
                ('away_team_yellow_cards', models.IntegerField()),
                ('home_team_red_cards', models.IntegerField()),
                ('away_team_red_cards', models.IntegerField()),
                ('home_team_total_goal_full_time', models.IntegerField()),
                ('away_team_total_goal_full_time', models.IntegerField()),
                ('home_team_total_goal_full_time_as_home', models.IntegerField()),
                ('away_team_total_goal_full_time_as_away', models.IntegerField()),
                ('home_team_total_goal_half_time', models.IntegerField()),
                ('away_team_total_goal_half_time', models.IntegerField()),
                ('home_team_total_goal_half_time_as_home', models.IntegerField()),
            ],
        ),
    ]
