# Generated by Django 2.2.10 on 2020-02-25 22:12

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20200225_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_yellow_cards', models.IntegerField()),
                ('away_yellow_cards', models.IntegerField()),
                ('home_red_cards', models.IntegerField()),
                ('away_red_cards', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
    ]
