# Generated by Django 2.2.10 on 2020-02-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20200225_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='num_matches',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
