# Generated by Django 2.2.10 on 2020-02-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20200226_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='totals',
            name='away_team_total_goal_conceded_full_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_goal_conceded_full_time_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_goal_conceded_half_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_goal_conceded_half_time_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_goal_conceded_second_half_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_goal_conceded_second_half_time_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_goal_conceded_full_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_goal_conceded_full_time_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_goal_conceded_half_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_goal_conceded_half_time_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_goal_conceded_second_half_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_goal_conceded_second_half_time_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
