# Generated by Django 2.2.10 on 2020-02-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20200226_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='totals',
            name='away_team_total_corners_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_corners_conceded_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_fouls_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_fouls_conceded_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_shots_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_shots_conceded_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_shots_conceded_on_target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_shots_conceded_on_target_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_corners_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_corners_conceded_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_fouls_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_fouls_conceded_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_shots_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_shots_conceded_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_shots_conceded_on_target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_shots_conceded_on_target_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
