# Generated by Django 2.2.10 on 2020-02-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_auto_20200226_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='totals',
            name='away_team_total_red_cards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_red_cards_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_red_cards_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_red_cards_conceded_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_yellow_cards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_yellow_cards_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_yellow_cards_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='away_team_total_yellow_cards_conceded_as_away',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_red_cards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_red_cards_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_red_cards_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_red_cards_conceded_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_yellow_cards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_yellow_cards_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_yellow_cards_conceded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totals',
            name='home_team_total_yellow_cards_conceded_as_home',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
